### PR TITLE
bump kubernetes to 1.3.4

### PR DESCRIPTION
**Pull request by jmhodges**
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v133 for details on what changes this includes.

### CODE REVIEW

**Comment by jmhodges** [comment]
Oh, there's a kubenetes 1.3.5 that hasn't hit GKE yet. 

Would you prefer going straight to that?

**Comment by andypost** [comment]
I think it makes sense to update to latest version

**Comment by jmhodges** [comment]
Ah, will post a PR but blocked on testing it locally on #14

**Comment by jmhodges** [comment]
Closing this in favor of #16 but unable to test it.

**Pull request closed without merging**
